name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  updateReadme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: update readme
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
